// Base on gh64
// https://github.com/gecko0307/gh64

const template = require("es6-template-strings");
const compile = require("es6-template-strings/compile");
const resolveToString = require("es6-template-strings/resolve-to-string");
const fs = require("fs");  
const util = require("util");
const path = require("path");

function requireUncached(module) {
    delete require.cache[require.resolve(module)];
    return require(module);
}

function processFont(fontsDir, configDir, font) {  
    const fontFamily = font.family || "";
    const fontFile = path.join(fontsDir, font.file || "");
    const whitelist = font.whitelist || "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890.,:;!?-+*/=><@#¹$%^&()[]{}|";
    const cssTemplateFilename = path.join(configDir, font.cssTemplate || "font.template.css");
    
    console.log(whitelist);

	function strToHex(str)
    {
		let result = "";
		for (let i = 0; i < str.length; i++)
        {
		    result += "U+" + str.charCodeAt(i).toString(16) + ",";
		}
		return result;
	}

	const glyphhanger = "glyphhanger";
	const commandTemplate = "%s --whitelist=%s --formats=woff --subset=%s";
	const cssTemplate = compile(fs.readFileSync(cssTemplateFilename, "utf8"));
	const command = util.format(commandTemplate, glyphhanger, strToHex(whitelist), fontFile);

	console.log(command);

	require("child_process").execSync(command, function(err, stdout, stderr)
    {
		if (err)
        {
			return console.log(err);
		}
	});
	
	var woffFile = util.format(path.join(fontsDir, "%s-subset.woff"), path.parse(fontFile).name);
	var woffData = fs.readFileSync(woffFile);
	var woffDataBase64 = woffData.toString("base64");
	var css = resolveToString(cssTemplate, {font_family: fontFamily, font_data: woffDataBase64});
	
	return css;
}

const comment = "/* Generated by webfontgen.js */\n";

function generateFonts()
{
    const fonts = requireUncached(path.resolve("./src/fonts.json"));
    const fontsDir = path.resolve("./fonts");
    const configDir = path.resolve("./src");
    const outputDir = path.resolve("./");
            
	var css = comment;
	Object.keys(fonts).forEach(function(key)
    {
		css += processFont(fontsDir, configDir, fonts[key]);
	});

	fs.writeFile(path.join(outputDir, "fonts.css"), css, function(err)
    {
		if (err)
			return console.log(err);
		else
			console.log("Success!");
	});
}

module.exports = generateFonts;
